### ISSUE TITLE
Feature: Channel Isolation / Optimization Guide

### ISSUE THREAD

**Issue by Sloanstar** [hazarjast/5g_rpi4_build#1]
I know most of this will be carrier specific, but I'm trying to determine how to optimize my connectivity. I've got a similar setup albeit a different carrier. I'm using the Waveshare 4G/5G Pihat with a RM502Q-AE. I can't seem to get speedtest above 20Mbit down.

**Comment by hazarjast** [comment]
What is your interface driver, MBIM, QMI, PPP? What is your network mode (WCDMA, LTE, NR NSA, NR SA) and servingcell info? Have you tested the same SIM in a phone or tablet to get a baseline for the expected Speedtest result?

**Comment by Sloanstar** [comment]
> What is your interface driver, MBIM, QMI, PPP? What is your network mode (WCDMA, LTE, NR NSA, NR SA) and servingcell info? Have you tested the same SIM in a phone or tablet to get a baseline for the expected Speedtest result?

QMI, not sure how to get some of the info you're looking for. 
I did try the sim in a phone, 373mbps down and 15.2mbps up.

**Comment by hazarjast** [comment]
No worries. With a result of 20Mbps that sounds like ModemManager maybe trying to use PPP (serial interface) for the connection instead of USB, or you have connected to a strong WCDMA cell. I would first check your modem status with mmcli:
`mmcli -L` will show the current numeric ID of the modem.

From there you can view the status:
`mmcli -m [modem_ID]`

Under 'System' section of the output it should show something like 'cdc-wdm0' as its 'primary port'. If it shows something else like 'ttyUSBx' then MM is connecting over raw serial and your QMI driver package is missing or otherwise not being used due to some missing or improper configuration.

If your 'primary port' is a 'cdc-wdm*' device then that confirms QMI is working and should rule out the interface type as a potential issue. I would next check your radio mode to try and rule out if the modem is connected over legacy WCDMA or not:
`qcom AT+QNWPREFCFG=\"mode_pref\"`

Ideally, that should return "+QNWPREFCFG: "mode_pref",LTE:NR5G", If it comes back showing "AUTO" or with a list that includes "WCDMA" I would then set it to LTE & NR only:
`qcom AT+QNWPREFCFG=\"mode_pref\",LTE:NR5G`

As most areas do not have NR SA fully live yet, you could also disable that to ensure the modem is using NR NSA which gives the best aggregate speed in most areas (this is covered in the repo README so maybe you have done this already):
```
qcom AT+CFUN=0
qcom AT+QNWPREFCFG=\"nr5g_disable_mode\",1
qcom AT+CFUN=1,1
```

From there I would retest and see if any of the changes made a difference. If not you should then obtain your serving cell info:
`qcom AT+QENG=\"servingcell\"`

If the modem is properly connected in NSA mode the output should have 3 lines. The first will say something like "NOCONN", the second will be your LTE anchor band, and the third will be the NR band you are aggregated with. Lines 2 and 3 will also include cell identifier and signal information which is helpful (i.e. if signal is bad, speeds will be bad).

If you have validated all of this and have a good signal from your serving cell then likely the issue lies with your carrier provisioning and/or some ID mismatch with the modem. Keep in mind that in the case of many carriers in the USA to have 5G speeds, you must be on a 5G plan with a 5G device IMEI and be using an appropriate 5G APN. If you are missing any one of these then you may see decreased speed, connect only on LTE (which would be evidenced in the "servingcell" output), or not connect at all.

Since I have no direct experience with the Waveshare hat, there is always a possibility of a hardware issue there on the USB interface as well but I doubt this since it is at least establishing a connection and achieving 3G/4G speeds.

**Comment by Sloanstar** [comment]
```
  System   |                  device: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-1
           |                 drivers: qmi_wwan, option1
           |                  plugin: quectel
           |            primary port: cdc-wdm0
           |                   ports: cdc-wdm0 (qmi), ttyUSB0 (qcdm), ttyUSB1 (ignored),
           |                          ttyUSB2 (at), wwan0 (net)
```

It's probably good that you don't have experience with the waveshare hat. I had to solder 2 of the antenna connectors back on to the board, it appears they couldn't support the weight of themselves. I did order a dual nic board with integrated m2 slot but it requires a cm4 module which are in short supply still.

Looks like preference mode was set to auto, I've adjusted that.
I did try disabling NR SA as you had to in the write-up but I since factory reset as i didn't see a difference. I'll try it again.
My SIM is from a t-mobile home internet router that is supposed to have 5g capabilities (FAST 5688W) so there shouldn't be a provisioning issue there.

**Comment by Sloanstar** [comment]
```
root@piwan:~# mmcli -m 0 --signal-get
  ----------------------
  Signal | refresh rate: 10 seconds
  ----------------------
  LTE    |         rssi: -68.00 dBm
         |         rsrq: -20.00 dB
         |         rsrp: -107.00 dBm
         |          s/n: -4.80 dB
  ----------------------
  5G     |         rsrq: -17.00 dB
         |         rsrp: -112.00 dBm
         |          s/n: 0.00 dB

root@piwan:~# speedtest
Retrieving speedtest.net configuration...
Testing from T-Mobile USA (x.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
[15.99 km]: 76.109 ms
Testing download speed................................................................................
Download: 42.06 Mbit/s
Testing upload speed......................................................................................................
Upload: 2.21 Mbit/s
```
A little better maybe....
I'm disabling the NR SA now. Is this something you know from the industry and a bit of experimentation?
Is there a way to dump out all the 'QNWPREFCFG' parameters?

**Comment by Sloanstar** [comment]
```
           |                   state: connected
           |             power state: on
           |             access tech: lte
           |          signal quality: 75% (cached)


Selecting best server based on ping...
[124.94 km]: 67.702 ms
Testing download speed................................................................................
Download: 38.00 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.45 Mbit/s

```
previous was access tech: 5g, this one is LTE - still about the same speeds   :/
Going to try a different carrier.

**Comment by hazarjast** [comment]
> FAST 5688W

What APN are you using with the SIM when used with the RM502Q-AE? Also, have you "repaired" the modem so it's IMEI is matching the gateway? There may be some difference when attaching to the T-Mobile network when using a TMHI SIM inside a non-TMHI approved device. At the very least, if you have a phone or tablet SIM to test with alongside the TMHI SIM, it might give some insight. You may also want to try updating your modem firmware and/or changing the MBN to Generic (vs Commercial-TMO which is likely auto-selected for you based on SIM).

I am going to go ahead and close this one out since it seems to be related to modem configuration and/or specific service provisioning as opposed to any flaws in the build instructions but feel free to reply with any updates as they might be instructive to others using your Waveshare hardware with TMHI.

**Comment by Sloanstar** [comment]
Grabbed an AT&T SIM - it's even worse throughput wise.
I've also got a new waveshare board that's 4g/5g dual nic but requires a pi CM4, which it probably going to be impossible to get. So stuck w/ the pi and the hat for now.

```
root@piwan:~# qcom at+qrsrp

+QRSRP: -97,-103,-111,-104,LTE
+QRSRP: -115,-112,-108,-109,NR5G

OK
root@piwan:~# qcom at+qsinr

+QSINR: -8,0,9,-5,NR5G

OK

# qcom AT+QENG=\"servingcell\"

+QENG: "servingcell","NOCONN"
+QENG: "LTE","FDD",310,410,AD2AD08,61,1000,2,3,3,330D,-98,-20,-60,7,5,210,-
+QENG: "NR5G-NSA",310,410,762,-110,1,-15,651360,77,6,1
```

**Comment by hazarjast** [comment]
Very odd. If repair/magic has been done and you have tested with the generic MBN then I am at a loss to explain the poor performance as compared to the same SIM in its native device. As a sanity check I would recommend trying to pull the signal stats from the native device to compare with your signal on the Waveshare setup and possibly reflash the modem with the latest available firmware update. Hopefully, the new Waveshare host board will show improvement.

**Comment by Sloanstar** [comment]
Got the new waveshare board and was able to score the 8GB WiFi CM4 by way of Germany and a parcel forwarding service....
Things are a little better with it, around 100 Mbit down, still a lousy 4-8 Mbit up. w/ IMEI repaired and verified 5G NSA. connected.

Anyone looking to do a build I recommend going the Integrated CM4 board over the pi hat due to construction quality.

root@piwan:~# qcom AT+QENG=\"servingcell\"

+QENG: "servingcell","NOCONN"
+QENG: "LTE","FDD",310,410,ACC13CB,227,67086,66,3,3,3303,-106,-11,-79,15,9,20,-
+QENG: "NR5G-NSA",310,410,762,-101,20,-11,651360,77,6,1

```
root@piwan:~# mmcli -m 0 --signal-get
  ----------------------
  Signal | refresh rate: 10 seconds
  ----------------------
  LTE    |         rssi: -77.00 dBm
         |         rsrq: -12.00 dB
         |         rsrp: -106.00 dBm
         |          s/n: 5.20 dB
  ----------------------
  5G     |         rsrq: -11.00 dB
         |         rsrp: -101.00 dBm
         |          s/n: 200.00 dB
```
Not sure how a 200dB SNR is possible....

Either way it should do in a pinch as a backup connectivity method should my primary fail.

Also wanted to share a little update to the TTL script since the newer OpenWRT has moved to nft for the firewall.

**/etc/config/firewall**  Append to the end
```
config include
        option path '/etc/firewall.user'
        option fw4_compatible '1'
```

**/etc/firewall.user** New File
```
nft add rule inet fw4 mangle_forward oifname wwan0 ip ttl set 65
```
