### ISSUE TITLE
custom firewall rules not working

### ISSUE THREAD

**Issue by droideggs** [hazarjast/5g_rpi4_build#3]
I used the custom firewall TTL rules but data usage is still being detected. Would you happen to have an updated TTL rule by any chance? Your guide was thorough and used it for my Verizon LTE module. I do have the RM502Q-AE on the way however.

**Comment by hazarjast** [comment]
As long as you’re using an OpenWRT 21.x build the rules should roughly be the same but actual TTL value can vary by carrier or your interface specification may be incorrect.

**Comment by droideggs** [comment]
I'm using the openwrt 21.02.5 build. would you happen to know what inerface specification that could be incorrect that would prevent it from working? i have the correct APN "vzwinternet" on Verizon network. From my understanding ttl of 65 should be the correct setting. 

I also added the following in /etc/sysctl.conf but it didn't seem to make a difference. 
net.ipv4.ip_default_ttl=65
net.ipv6.ip_default_ttl=65

**Comment by hazarjast** [comment]
I wouldn’t mess with /etc/sysctl.conf, that’s not going to help. For interface help please screenshot your Network Interfaces page from the GUI so I can see what you have. Also please copy/paste your actual rules so I can see those as well.

Verizon is wacky, some plans work with 64, others 88, still some others 117.

**Comment by droideggs** [comment]
here is the screenshot of my network interfaces tab. i removed the edits from sysctl.conf as well. Thanks and appreciate your help thus far. essentially im just using the raspberry pi 3b+ connected to a SIM7600G-H module

![Screenshot 2023-04-14 at 5 07 29 AM](https://user-images.githubusercontent.com/7389886/232039836-5175b609-35e7-4c8f-b681-f0167d157205.png)

**Comment by hazarjast** [comment]
Interface still appears as wwan0 so that’s likely not it. Please paste your complete custom firewall rules here for review.

**Comment by droideggs** [comment]
![image](https://user-images.githubusercontent.com/7389886/232041274-6a517ab3-08bf-45b6-9c81-71177f5abfea.png)

**Comment by droideggs** [comment]
sorry to ping but did you see the image i sent above? 

the custom ttl rules are the same ones you provided in your tutorial.

**Comment by hazarjast** [comment]
Sorry, I started my work day so had to wait until lunch break to review your screenshot. It looks okay and I don't see any issue with it. My only question now would be how you are validating that hotspot data is being used? Are you checking the Verizon app or portal which is showing hotspot usage on your line? If so then you can try one of the other TTL values I suggested (restarting each time for the new test value to take effect).

Outside of trying the other TTL values I could not say why you would still be seeing hotspot usage unless your SIMCom modem has some sort of carrier profile which reveals itself to the carrier. I know nothing of SIMCom to be able to say if there is some identification of IMEI which may attribute all usage to hotspot or if your specific provisioned Verizon plan has something unique which is contributing to the issue.

**Comment by droideggs** [comment]
yeah im checking through the Verizon portal (mobile app and website) and seeing the hotspot data usage increasing. 

ill use the other ttl values you mentioned. 

i am using a mobile hotspot plan. wondering if thats the reason why? or does the plan need to be a strictly mobile plan for this to work? 

the RM502Q-AE hat is coming today so ill give that one a go and see if that makes a difference. i only got the SIM7600G-H as a test before the RM502Q-AE arrived, because I'm impatient like that lol. I'll be returning the SIMcom module once I have the RM502Q-AE hat ready.

**Comment by hazarjast** [comment]
If you're using a mobile hotspot plan then TTL mangle is not useful. It is a hack meant for plans with a separate hotspot bucket of data like phone or tablet. For hotspot plans the data is always hotspot data so you should remove the custom firewall rules :)

Given this information, the SIMCom and Quectel are likely to produce the same result.

**Comment by droideggs** [comment]
why is it then when i search around on forums there are folks that are on mobile hotspot plans that are getting unlimited data using ttl modification? the mobile hotspot plan im using provisions its own number, has sms and talk capability too.

**Comment by hazarjast** [comment]
I think maybe there is some confusion by those on the forums you reference. If the plan is sold as an official hotspot plan directly from the carrier it is usually limited to a certain amount of data like 50-100GB (less or more depending on plan) and does not need TTL but is also not unlimited. There are some business hotspot plans which are unlimited in the US but they are rate-limited (meaning the speed is capped). There are special organizations which sell hotspot plans like Calyx institute which offer unlimited data but again these do not need TTL and if you do mangle TTL it likely will affect things like video streaming bandwidth etc.

TTL mangle is a hack meant for plans which are provisioned for tablets/phones only since they have a separate data "bucket" for hotspot usage. All cellular devices get a number provisioned to them but it does not mean it will allow you to actually receive calls/texts (SMS more likely than VoLTE calls at least with what I've found testing tablet plans). What is the exact name of your provisioned plan? That should give confirmation if it is truly a hotspot plan or not.

**Comment by droideggs** [comment]
maybe it is because im specifically on the hotspot plan thats preventing me from using the mobile data bucket as you mentioned. verizon shows my second line as part of the 'plus' mobile hotspot plan. if the other ttl values don't work i will just add another line which from my understanding is only an extra $10/month. I can test it out by swapping to my primary mobile number sim card and seeing if data usage goes up just to confirm as well.
![Screenshot 2023-04-14 at 1 54 47 PM](https://user-images.githubusercontent.com/7389886/232153489-27f7581f-14c1-4241-891c-1125359c4edc.png)

![Screenshot 2023-04-14 at 1 51 43 PM](https://user-images.githubusercontent.com/7389886/232153535-4d9ea11d-c5f4-471b-aca8-1c9abd869c51.png)

**Comment by hazarjast** [comment]
As per the FAQ, your plan is a phone plan (https://www.verizon.com/support/get-more-unlimited-faqs/) thus it has unlimited on-device (phone) data and a separate bucket for hotspot data. So, the TTL mangle would be helpful to you if you could get it working so that you don't use up your 50GB of available hotspot data. I have no idea what the $20 "Plus" add-on is and if it has any affect on hotspot data or not. I couldn't seem to find out anything about it when I checked Verizon's site.

**Comment by droideggs** [comment]
the "Plus" plan is a mobile hotspot plan only essentially. i'll let you know how it goes after modifying to different TTL values, and if that doesn't work ill swap out to my primary phone sim card. thanks for all your help thus far. i get 50% off the hotspot plan hence why i took advantage of it. 
![Screenshot 2023-04-14 at 2 10 41 PM](https://user-images.githubusercontent.com/7389886/232155749-221623fc-48e2-4782-82e3-8f220757a0d1.png)

**Comment by hazarjast** [comment]
Man I thought Verizon LTE unlimited plans were confusing but I think 5G plans for them now take the cake, lol. So if one has a "5G Get More" plan with the included 50GB of included hotspot, does adding the "Plus" just add another 50GB of hotspot for a total of 100GB hotspot data and on-device (phone) data is still unlimited? Sorry if I'm misunderstanding.

But yes, you'll have to test the different TTL values and see if any of them work for your provisioned plan.

**Comment by droideggs** [comment]
yeah pretty much lol. just adds another 50GB of data. I should have just added another mobile line, but I believe that second line will dip into the primary line's 50GB of hotspot cap.

**Comment by droideggs** [comment]
quick update:

RM502Q-AE will still show data usage on my hotspot plan. 

I switched to a Mint Mobile sim card (only 4GB of premium data) but I was getting north of 100mbps and it was probably bottlenecked by the built in wifi module on the raspberry pi.

The only way to get truly unlimited data without bottlenecks is to get a plan that has no throttling on the mobile plan and those cost up to $70+ per month which kinda makes it not worth it. 

oh and btw, Verizon does not like 5G SA mode so it needs to be disabled in AT commands. That can be done by going into minicom and entering AT+QNWPREFCFG="nr5g_disable_mode",1

without the command above I was not even able to log into the Verizon network

even on a tablet plan, ill only get 30GB of premium data then I will get throttled, so that wont be worth it neither even with TTL modification

**Comment by hazarjast** [comment]
Thanks for the updates. I'm not sure how heavy handed Verizon's deprioritization is but TMO's is mostly unnoticeable for me after my plan's 50GB limit so I wouldn't really refer to it as a throttle. This of course can vary greatly if the towers in your market are at capacity or not. Not all carriers support SA yet in all markets and even then it may depend on the registered device TAC if it is allowed to attach under SA.

In terms of general restrictions on 5G I would say Verizon has probably unnecessarily complicated it the most, followed by AT&T. My hope is the Verizon will be forced to simplify their 5G offerings in the months/years to come as they face strong competition. Most of those I know that need Verizon (i.e. can't get a good AT&T or TMO signal) instead use US Mobile or Visible as their unlimited offerings on VZW's network are much more straightforward.

Since there does not seem to be a technical bug or problem with the TTL rules presented in the guide I'm going to go ahead and close out this open issue. Wish you success with your VZW testing!
