### ISSUE TITLE
IP-PASSTRHOUGH

### ISSUE THREAD

**Issue by Madjidoid** [hazarjast/5g_rpi4_build#4]
Hello,
I have a rm502q-ae 5g modem connected to a raspberry pi 3B via usb and i want to install a vpn server on it. I installed wireguard vpn and i configured the tunnel but i'm not able to connect from the outside (public network) and i think it's because i'm not doing a port forwarding from the internet back to LAN.  Knowing that i'm getting a public ip from the mobile network provider in France, can you please give more details about the solution you tried with Sprint for the IP-Passthrough.

**Comment by hazarjast** [comment]
Hi,
VPN server configuration on the modem RPi host would be fully outside the scope of support that I am able to provide for this project. I am aware that Sprint offered a static IP offering for consumer plans at one time but I did not use it and since they have merged with T-Mobile I do not believe that is an offering any longer. If your carrier offers a truly public IP and you cannot even perform a simple netcat or PortQry test to the listening WireGuard port on the RPi server, then there is either something on the RPi end which is blocking inbound traffic on that port, or your carrier may be blocking it.

To further clarify, IP-Passthrough and passing WireGuard traffic to a server on the RPi would be two entirely different things. For RAW IP interfaces configured on the RM502Q-AE via QMI or MBIM, ModemManager creates a pseudo interface which is not a true Ethernet interface, thus true bridging or IP-Passthrough is not possible. There are other configurations not using ModemManager which you can research to provide an IPPT or close to IPPT solution but again these would be well outside the scope of this project as I only offer an explanation on DMZ since I am using ModemManager here.
